name: backend_deploy
on:
  push:
    branches: main

  jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          branch: "main"
          envkey_USER: ${{secrets.USER}}
          envkey_PASSWORD: ${{secrets.PASSWORD}}
          envkey_DB: ${{secrets.DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: /back-end
          file_name: .env
          fail_on_empty: true

      - name: front-end env file
          uses: SpicyPizza/create-envfile@v1.3
          with:
            envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
            directory: /front-end
            file_name: .env
            fail_on_empty: true

      - name: Build
          run: docker-compose build

      - name: Run
          run: docker-compose down && docker-compose up -d