name: backend_deploy
on:
  push:
    branches: main

  jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # colocar configuração de keys aki
          branch: "main"